export const Config = {
  SERVER_URL: process.env.EXPO_PUBLIC_SERVER_URL!,  
  GOOGLE_WEB_CLIENT_ID:process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID!,
  GOOGLE_IOS_CLIENT_ID:process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID!
};
